name: R Package Installation Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-package:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    - name: Install package dependencies
      run: |
        # Get the package tarball name
        PKG_TARBALL=$(ls *.tar.gz)
        
        # Install remotes package for dependency handling
        Rscript -e 'install.packages("remotes")'
        
        # Install dependencies from the package description
        Rscript -e "remotes::install_deps('.')"

    - name: Test package installation and basic functionality
      run: |
        # Get the package tarball name
        PKG_TARBALL=$(ls *.tar.gz)
        
        # Extract package name from tarball (remove version and extension)
        PKG_NAME=$(basename "$PKG_TARBALL" | sed 's/_[0-9].*.tar.gz//')
        
        # Install the package
        R CMD INSTALL ${PKG_TARBALL}
        
        # Test if we can load and use the package
        Rscript -e "
          # Load the package
          library($PKG_NAME)
          
          # Try to run the main function
          make_figures()
          
          # If we get here without error, test passed
          cat('Package test successful!\n')
        " 